---
language: cpp
os: linux
dist: bionic
cache:
    - directories:
          - $HOME/.ccache
          - $HOME/.conan
          - $HOME/.conan-clang11
notifications:
    email:
        recipients:
            - michel.estermann@bbv.ch
        on_success: change
        on_failure: always
jobs:
    include:
        - os: osx
          compiler: clang
          osx_image: xcode11.2
          addons:
              homebrew:
                  packages:
                      - qt
                  update: false
          install:
              - python3 -m pip install --upgrade pip setuptools
              - python3 -m pip install conan cmake
              - conan --version
          before_script:
              - export Qt5_DIR=/usr/local/opt/qt/lib/cmake
              - cmake -S . -B ./build -G"Unix Makefiles" -DENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=Release
          script:
              - cmake --build ./build -- -j16
              - (cd ./build && ctest -j2)
        - os: linux
          dist: focal
          compiler: gcc
          addons:
              apt:
                  sources:
                      - sourceline: ppa:beineri/opt-qt-5.15.2-focal
                  update: true
                  packages:
                      - ninja-build
                      - qt515base
                      - qt515charts-no-lgpl
                      - qt515tools
                      - libc6-dev
                      - libgl-dev
                      - libgl1-mesa-dev
                      - mesa-common-dev
          install:
              - python3 -m pip install --upgrade pip setuptools
              - python3 -m pip install conan cmake
              - conan --version
          before_script:
              - /opt/qt515/bin/qt515-env.sh
              - cmake -S . -B ./build -G"Ninja" -DCMAKE_BUILD_TYPE=Release
          script:
              - cmake --build ./build -- -j16
              - (cd ./build && ctest -j2)